FROM node:20-alpine

WORKDIR /app

# 复制整个 standalone 目录结构
COPY .next/standalone ./standalone

# 复制静态资源
COPY .next/static ./.next/static
COPY public ./public

ENV NODE_ENV=test
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

EXPOSE 3000

# 启动命令需要指向正确的路径
CMD ["node", "standalone/next-frontend/server.js"]